
package Vista;
import Modelo.*;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controlador.*;
public class Pruebita extends javax.swing.JFrame {

    /**
     * Creates new form Pruebita
     */
    public Pruebita() {
        
        initComponents();
    jPanelHornosSolares.setVisible(false);
    jPanelMantenimiento.setVisible(false);
    jPanelFuncionamiento.setVisible(false);
    jPanelAmbiente.setVisible(false);
    jPanelAutosustentable.setVisible(false);
    ClaseConsulta misConsultas = new ClaseConsulta();
    tblDatoHorno.setModel(misConsultas.MostrarHornos());
    tblDatoReparacion.setModel(misConsultas.MostrarReparacion());
    tblDatoFuncionamiento.setModel(misConsultas.consultaHornos());        
    tblDatoAutosustentable.setModel(misConsultas.consultaAutosustentable());
    tblDatoAmbiente.setModel(misConsultas.consultaHornos());
    tblDatoMantenimiento.setModel(misConsultas.consultaHornos());

    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHornosSolares = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txb_reflectores = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txb_materiales = new javax.swing.JTextArea();
        btn_IngresarHornos = new javax.swing.JButton();
        cb_estadohorno = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDatoHorno = new javax.swing.JTable();
        Jd_fecha1 = new com.toedter.calendar.JDateChooser();
        txb_tipo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txb_dimensiones = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanelMantenimiento = new javax.swing.JPanel();
        txtIDMantenimiento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Jd_fecha = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDatoReparacion = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txb_detallesr = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txb_materialesr = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblDatoMantenimiento = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        btn_IngresarMantenimiento = new javax.swing.JButton();
        jPanelFuncionamiento = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        tblDatoFuncionamiento = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtIDFuncionamiento = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        btn_IngresarFuncionamiento = new javax.swing.JButton();
        txb_tiempoc = new com.toedter.calendar.JSpinnerDateEditor();
        js_temperaturai = new javax.swing.JSpinner();
        cb_tipodealimento = new javax.swing.JComboBox<>();
        cb_estadohorno1 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        rbManual = new javax.swing.JRadioButton();
        rbAutomatico = new javax.swing.JRadioButton();
        js_Hora = new com.toedter.calendar.JSpinnerDateEditor();
        jLabel36 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jb_fechaoperacion = new com.toedter.calendar.JDateChooser();
        jLabel38 = new javax.swing.JLabel();
        jPanelAutosustentable = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        btn_IngresarAutosustentable = new javax.swing.JButton();
        js_energiarecibida = new javax.swing.JSpinner();
        jLabel47 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txb_consumoe = new javax.swing.JTextField();
        txb_energiaalmacenada = new javax.swing.JTextField();
        Jd_fecha4 = new com.toedter.calendar.JDateChooser();
        cb_eficienciaenergetica = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        tblDatoAutosustentable = new javax.swing.JTable();
        jLabel51 = new javax.swing.JLabel();
        txtIDAutosustentable = new javax.swing.JTextField();
        jPanelAmbiente = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        btn_IngresarAmbiente = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        txb_direccion = new javax.swing.JComboBox<>();
        txb_angulo = new javax.swing.JSpinner();
        jLabel59 = new javax.swing.JLabel();
        txb_temperatura = new javax.swing.JSpinner();
        txb_intensidadsolar = new javax.swing.JComboBox<>();
        Jd_fecha6 = new com.toedter.calendar.JDateChooser();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblDatoAmbiente = new javax.swing.JTable();
        txtIDAmbiente = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        lblMantenimiento = new javax.swing.JLabel();
        lblHorno = new javax.swing.JLabel();
        lblFuncionamiento = new javax.swing.JLabel();
        lblAmbiente = new javax.swing.JLabel();
        lblAutosustentable = new javax.swing.JLabel();
        jPanelFondo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHornosSolares.setBackground(new java.awt.Color(102, 102, 102));
        jPanelHornosSolares.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Fecha creacion");
        jPanelHornosSolares.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 229, -1, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Reflectores");
        jPanelHornosSolares.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 88, -1, -1));

        txb_reflectores.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jPanelHornosSolares.add(txb_reflectores, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 116, 153, -1));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Sistema de aislamiento");
        jPanelHornosSolares.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 155, -1, -1));

        txb_materiales.setColumns(20);
        txb_materiales.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        txb_materiales.setLineWrap(true);
        txb_materiales.setRows(5);
        txb_materiales.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txb_materiales);

        jPanelHornosSolares.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 254, 156, 65));

        btn_IngresarHornos.setBackground(new java.awt.Color(51, 153, 0));
        btn_IngresarHornos.setFont(new java.awt.Font("Gadugi", 1, 38)); // NOI18N
        btn_IngresarHornos.setForeground(new java.awt.Color(255, 255, 255));
        btn_IngresarHornos.setText("Ingresar");
        btn_IngresarHornos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_IngresarHornos.setBorderPainted(false);
        btn_IngresarHornos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarHornosActionPerformed(evt);
            }
        });
        jPanelHornosSolares.add(btn_IngresarHornos, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 354, 280, 63));

        cb_estadohorno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Aislamiento por material", "Doble cubierta transparente", "Sellado hermético", "Aislamiento reflectante" }));
        jPanelHornosSolares.add(cb_estadohorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 183, 153, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingreso de los Hornos Solares");
        jPanelHornosSolares.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 6, -1, -1));

        tblDatoHorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatoHornoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblDatoHorno);

        jPanelHornosSolares.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 276, 131));

        Jd_fecha1.setDateFormatString("yyyy-MM-dd");
        jPanelHornosSolares.add(Jd_fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 257, 153, 46));

        txb_tipo.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        txb_tipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txb_tipoFocusGained(evt);
            }
        });
        txb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txb_tipoActionPerformed(evt);
            }
        });
        jPanelHornosSolares.add(txb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 129, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Lista de hornos ingresados");
        jPanelHornosSolares.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 82, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tipo");
        jPanelHornosSolares.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 82, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Materiales");
        jPanelHornosSolares.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 226, -1, -1));

        txb_dimensiones.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        txb_dimensiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txb_dimensionesActionPerformed(evt);
            }
        });
        jPanelHornosSolares.add(txb_dimensiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 181, 129, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Dimensiones");
        jPanelHornosSolares.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 149, -1, -1));

        getContentPane().add(jPanelHornosSolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1070, 440));

        jPanelMantenimiento.setBackground(new java.awt.Color(91, 91, 91));
        jPanelMantenimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelMantenimiento.add(txtIDMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 85, -1));

        jLabel8.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hornos reparados");
        jPanelMantenimiento.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));

        Jd_fecha.setDateFormatString("yyyy-MM-dd");
        jPanelMantenimiento.add(Jd_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 313, 194, 33));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Detalles de la Reparacion");
        jPanelMantenimiento.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 76, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Materiales Remplazados");
        jPanelMantenimiento.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 201, -1, -1));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mantenimiento de los hornos");
        jPanelMantenimiento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Fecha creacion");
        jPanelMantenimiento.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 285, -1, -1));

        tblDatoReparacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDatoReparacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatoReparacionMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDatoReparacion);

        jPanelMantenimiento.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 420, 210));

        txb_detallesr.setColumns(20);
        txb_detallesr.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txb_detallesr.setRows(5);
        jScrollPane1.setViewportView(txb_detallesr);

        jPanelMantenimiento.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 104, 268, -1));

        txb_materialesr.setColumns(20);
        txb_materialesr.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txb_materialesr.setRows(5);
        jScrollPane2.setViewportView(txb_materialesr);

        jPanelMantenimiento.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 229, 268, 50));

        tblDatoMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatoMantenimientoMouseClicked(evt);
            }
        });
        jScrollPane13.setViewportView(tblDatoMantenimiento);

        jPanelMantenimiento.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 220, 130));

        jLabel31.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Lista de hornos ingresados");
        jPanelMantenimiento.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        btn_IngresarMantenimiento.setBackground(new java.awt.Color(51, 153, 0));
        btn_IngresarMantenimiento.setFont(new java.awt.Font("Gadugi", 1, 38)); // NOI18N
        btn_IngresarMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        btn_IngresarMantenimiento.setText("Ingresar");
        btn_IngresarMantenimiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_IngresarMantenimiento.setBorderPainted(false);
        btn_IngresarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarMantenimientoActionPerformed(evt);
            }
        });
        jPanelMantenimiento.add(btn_IngresarMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 232, -1));

        getContentPane().add(jPanelMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1100, 440));

        jPanelFuncionamiento.setBackground(new java.awt.Color(102, 102, 102));
        jPanelFuncionamiento.setForeground(new java.awt.Color(255, 255, 255));
        jPanelFuncionamiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDatoFuncionamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDatoFuncionamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatoFuncionamientoMouseClicked(evt);
            }
        });
        jScrollPane15.setViewportView(tblDatoFuncionamiento);

        jPanelFuncionamiento.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 99, 220, 210));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Funcionamiento del Horno");
        jPanelFuncionamiento.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Temperatura Interna");
        jPanelFuncionamiento.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, -1, -1));
        jPanelFuncionamiento.add(txtIDFuncionamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 315, 56, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Datos operación");
        jPanelFuncionamiento.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 219, -1, -1));

        btn_IngresarFuncionamiento.setBackground(new java.awt.Color(51, 153, 0));
        btn_IngresarFuncionamiento.setFont(new java.awt.Font("Gadugi", 1, 38)); // NOI18N
        btn_IngresarFuncionamiento.setForeground(new java.awt.Color(255, 255, 255));
        btn_IngresarFuncionamiento.setText("Ingresar");
        btn_IngresarFuncionamiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_IngresarFuncionamiento.setBorderPainted(false);
        btn_IngresarFuncionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarFuncionamientoActionPerformed(evt);
            }
        });
        jPanelFuncionamiento.add(btn_IngresarFuncionamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 280, 63));

        txb_tiempoc.setDateFormatString("HH:mm:ss");
        txb_tiempoc.setEditor(new javax.swing.JSpinner.DateEditor(txb_tiempoc, "HH:mm:ss"));
        txb_tiempoc.setMaxSelectableDate(new java.util.Date(253370861999000L));
        txb_tiempoc.setMinSelectableDate(new java.util.Date(-62135758800000L));
        jPanelFuncionamiento.add(txb_tiempoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 167, 100, 39));

        js_temperaturai.setModel(new javax.swing.SpinnerNumberModel(0, 0, 360, 1));
        js_temperaturai.setName(""); // NOI18N
        jPanelFuncionamiento.add(js_temperaturai, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 168, 97, 36));

        cb_tipodealimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carnes y Aves", "Pescados y Verduras", "Panadería y", "Repostería", "Pastas", "Arroces y Guisos", "Otros" }));
        jPanelFuncionamiento.add(cb_tipodealimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 97, 109, 40));

        cb_estadohorno1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buen Estado", "Estado Decente", "Estado Regular", "Estado mal", "Estado para reparar" }));
        jPanelFuncionamiento.add(cb_estadohorno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 97, 99, 40));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Estado del Horno");
        jPanelFuncionamiento.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 69, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lista de hornos ingresados");
        jPanelFuncionamiento.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 69, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tipo de Alimento");
        jPanelFuncionamiento.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 69, -1, -1));

        rbManual.setForeground(new java.awt.Color(255, 255, 255));
        rbManual.setText("Ingreso manual de fechas");
        rbManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbManualActionPerformed(evt);
            }
        });

        rbAutomatico.setForeground(new java.awt.Color(255, 255, 255));
        rbAutomatico.setText("Ingreso automatico de fecha");
        rbAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAutomaticoActionPerformed(evt);
            }
        });

        js_Hora.setDateFormatString("HH:mm:ss");
        js_Hora.setEditor(new javax.swing.JSpinner.DateEditor(js_Hora, "HH:mm:ss"));
        js_Hora.setMaxSelectableDate(new java.util.Date(253370861999000L));
        js_Hora.setMinSelectableDate(new java.util.Date(-62135758800000L));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Fecha Operacion");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Hora de la Operacion");

        jb_fechaoperacion.setDateFormatString("yyyy-MM-dd");

        jDesktopPane1.setLayer(rbManual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rbAutomatico, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(js_Hora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jb_fechaoperacion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(rbManual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbAutomatico))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(js_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jb_fechaoperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel36))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbManual)
                    .addComponent(rbAutomatico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_fechaoperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelFuncionamiento.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 247, -1, -1));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Tiempo de Coccion");
        jPanelFuncionamiento.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 139, -1, -1));

        getContentPane().add(jPanelFuncionamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 900, 440));

        jPanelAutosustentable.setBackground(new java.awt.Color(71, 71, 71));
        jPanelAutosustentable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Eficiencia Energetica");
        jPanelAutosustentable.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 175, -1, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Consumo Energetico");
        jPanelAutosustentable.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 84, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("%");
        jPanelAutosustentable.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 142, -1, -1));

        btn_IngresarAutosustentable.setBackground(new java.awt.Color(51, 153, 0));
        btn_IngresarAutosustentable.setFont(new java.awt.Font("Gadugi", 1, 38)); // NOI18N
        btn_IngresarAutosustentable.setForeground(new java.awt.Color(255, 255, 255));
        btn_IngresarAutosustentable.setText("Ingresar");
        btn_IngresarAutosustentable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_IngresarAutosustentable.setBorderPainted(false);
        btn_IngresarAutosustentable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarAutosustentableActionPerformed(evt);
            }
        });
        jPanelAutosustentable.add(btn_IngresarAutosustentable, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 280, 63));

        js_energiarecibida.setModel(new javax.swing.SpinnerNumberModel(0, 0, 360, 1));
        js_energiarecibida.setName(""); // NOI18N
        jPanelAutosustentable.add(js_energiarecibida, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 210, 82, 30));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("w");
        jPanelAutosustentable.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 218, -1, -1));

        jLabel6.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Autosustentabilidad del horno");
        jPanelAutosustentable.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        txb_consumoe.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txb_consumoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txb_consumoeActionPerformed(evt);
            }
        });
        jPanelAutosustentable.add(txb_consumoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 129, 79, -1));

        txb_energiaalmacenada.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanelAutosustentable.add(txb_energiaalmacenada, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 129, 84, -1));

        Jd_fecha4.setDateFormatString("yyyy-MM-dd");
        jPanelAutosustentable.add(Jd_fecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 289, 229, 38));

        cb_eficienciaenergetica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Alta", "Media", "Baja" }));
        jPanelAutosustentable.add(cb_eficienciaenergetica, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 203, 119, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha creacion");
        jPanelAutosustentable.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 261, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("w");
        jPanelAutosustentable.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 142, -1, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Energia Solar Recibida");
        jPanelAutosustentable.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 175, -1, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Lista de funciones");
        jPanelAutosustentable.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        tblDatoAutosustentable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDatoAutosustentable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatoAutosustentableMouseClicked(evt);
            }
        });
        jScrollPane14.setViewportView(tblDatoAutosustentable);

        jPanelAutosustentable.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 276, 131));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Energia Almacenada");
        jPanelAutosustentable.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 84, -1, -1));
        jPanelAutosustentable.add(txtIDAutosustentable, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 56, -1));

        getContentPane().add(jPanelAutosustentable, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 910, 440));

        jPanelAmbiente.setBackground(new java.awt.Color(58, 58, 58));
        jPanelAmbiente.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAmbiente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Lista de hornos ingresados");
        jPanelAmbiente.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        btn_IngresarAmbiente.setBackground(new java.awt.Color(51, 153, 0));
        btn_IngresarAmbiente.setFont(new java.awt.Font("Gadugi", 1, 38)); // NOI18N
        btn_IngresarAmbiente.setForeground(new java.awt.Color(255, 255, 255));
        btn_IngresarAmbiente.setText("Ingresar");
        btn_IngresarAmbiente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_IngresarAmbiente.setBorderPainted(false);
        btn_IngresarAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarAmbienteActionPerformed(evt);
            }
        });
        jPanelAmbiente.add(btn_IngresarAmbiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 359, 280, 63));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Dirección del Sol");
        jPanelAmbiente.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 211, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Fecha creacion");
        jPanelAmbiente.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 257, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("°");
        jPanelAmbiente.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 163, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Intensidad Solar");
        jPanelAmbiente.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 134, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Angulo Solar");
        jPanelAmbiente.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 129, -1, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Temperatura");
        jPanelAmbiente.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 199, -1, -1));

        txb_direccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Norte", "Sur", "Este", "Oeste" }));
        jPanelAmbiente.add(txb_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 239, 130, 32));

        txb_angulo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 360, 1));
        txb_angulo.setName(""); // NOI18N
        jPanelAmbiente.add(txb_angulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 163, 100, 30));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("°C");
        jPanelAmbiente.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 227, -1, -1));

        txb_temperatura.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        txb_temperatura.setName(""); // NOI18N
        jPanelAmbiente.add(txb_temperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 227, 100, 30));

        txb_intensidadsolar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Alta", "Media", "Baja" }));
        jPanelAmbiente.add(txb_intensidadsolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 159, 140, 34));

        Jd_fecha6.setDateFormatString("yyyy-MM-dd");
        jPanelAmbiente.add(Jd_fecha6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 282, 160, 40));

        tblDatoAmbiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatoAmbienteMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(tblDatoAmbiente);

        jPanelAmbiente.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 220, 187));
        jPanelAmbiente.add(txtIDAmbiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 150, -1));

        jLabel60.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Ambiente del Horno");
        jPanelAmbiente.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 16, 330, -1));

        getContentPane().add(jPanelAmbiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 920, 440));

        jPanelPrincipal.setBackground(new java.awt.Color(102, 102, 102));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMantenimiento.setBackground(new java.awt.Color(102, 102, 102));
        lblMantenimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ix - maintenance-filled.png"))); // NOI18N
        lblMantenimiento.setText("Mantenimiento");
        lblMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMantenimientoMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(lblMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 186, 58));

        lblHorno.setBackground(new java.awt.Color(102, 102, 102));
        lblHorno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHorno.setForeground(new java.awt.Color(255, 255, 255));
        lblHorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ph - oven-fill.png"))); // NOI18N
        lblHorno.setText("Horno");
        lblHorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHornoMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(lblHorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 186, 58));

        lblFuncionamiento.setBackground(new java.awt.Color(102, 102, 102));
        lblFuncionamiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFuncionamiento.setForeground(new java.awt.Color(255, 255, 255));
        lblFuncionamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lsicon - operation-filled.png"))); // NOI18N
        lblFuncionamiento.setText("Funcionamiento");
        lblFuncionamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFuncionamientoMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(lblFuncionamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 186, 58));

        lblAmbiente.setBackground(new java.awt.Color(102, 102, 102));
        lblAmbiente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAmbiente.setForeground(new java.awt.Color(255, 255, 255));
        lblAmbiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tdesign - undertake-environment-protection-filled.png"))); // NOI18N
        lblAmbiente.setText("Ambiente");
        lblAmbiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAmbienteMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(lblAmbiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 186, 58));

        lblAutosustentable.setBackground(new java.awt.Color(102, 102, 102));
        lblAutosustentable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAutosustentable.setForeground(new java.awt.Color(255, 255, 255));
        lblAutosustentable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carbon - sustainability.png"))); // NOI18N
        lblAutosustentable.setText("Autosustentable");
        lblAutosustentable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAutosustentableMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(lblAutosustentable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 186, 58));

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 440));

        jPanelFondo.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1360, Short.MAX_VALUE)
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1360, 440));

        jLabel3.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestion de hornos solares");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 410, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblDatoAmbienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatoAmbienteMouseClicked
        int filaSeleccionada = tblDatoAmbiente.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tblDatoAmbiente.getModel();
        Object idObjeto = modelo.getValueAt(filaSeleccionada, 0);
        txtIDAmbiente.setText(String.valueOf(idObjeto));
    }//GEN-LAST:event_tblDatoAmbienteMouseClicked

    private void btn_IngresarAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarAmbienteActionPerformed
        // TODO add your handling code here:
        try {
            ClaseConsulta INGA = new ClaseConsulta();
            ambiente  a = new ambiente(
                Integer.parseInt(txtIDAmbiente.getText()),
                (String) txb_intensidadsolar.getSelectedItem(),
                (int) txb_angulo.getValue(),
                (int) txb_temperatura.getValue(),
                (String) txb_direccion.getSelectedItem(),
                new SimpleDateFormat("yyyy/MM/dd").format(Jd_fecha6.getDate())
            );
            INGA.IngAmbiente(a);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_btn_IngresarAmbienteActionPerformed

    private void txb_consumoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txb_consumoeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txb_consumoeActionPerformed

    private void btn_IngresarAutosustentableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarAutosustentableActionPerformed
        // TODO add your handling code here:
        try {
            ClaseConsulta INAU = new ClaseConsulta();
            autosustentable au = new autosustentable(
                Integer.parseInt(txtIDAutosustentable.getText()),
                Integer.parseInt(txb_consumoe.getText()),
                Integer.parseInt(txb_energiaalmacenada.getText()),
                (String) cb_eficienciaenergetica.getSelectedItem(),
                (int) js_energiarecibida.getValue(),
                new SimpleDateFormat("yyyy/MM/dd").format(Jd_fecha4.getDate())
            );
            INAU.IngresarAutosustentable(au);
            txb_consumoe.setText(null);
            txb_energiaalmacenada.setText(null);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_btn_IngresarAutosustentableActionPerformed

    private void rbAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAutomaticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAutomaticoActionPerformed

    private void rbManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbManualActionPerformed

    private void btn_IngresarFuncionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarFuncionamientoActionPerformed
        try {
            ClaseConsulta INFU = new ClaseConsulta();
            funciones f = new funciones(
                Integer.parseInt(txtIDFuncionamiento.getText()),
                (int)(js_temperaturai.getValue()),
                 new SimpleDateFormat("HH:mm:ss").format(txb_tiempoc.getValue()),
                (String)cb_tipodealimento.getSelectedItem(),
                (String) cb_estadohorno.getSelectedItem(),
                 new SimpleDateFormat("yyyy/MM/dd").format(jb_fechaoperacion.getDate()),
                  new SimpleDateFormat("HH:mm:ss").format(js_Hora.getValue())
            );
            INFU.InsertarFuncion(f);

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_btn_IngresarFuncionamientoActionPerformed

    private void tblDatoFuncionamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatoFuncionamientoMouseClicked
        int filaSeleccionada = tblDatoFuncionamiento.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tblDatoFuncionamiento.getModel();
        Object idObjeto = modelo.getValueAt(filaSeleccionada, 0);
        txtIDFuncionamiento.setText(String.valueOf(idObjeto));
    }//GEN-LAST:event_tblDatoFuncionamientoMouseClicked

    private void tblDatoReparacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatoReparacionMouseClicked

    }//GEN-LAST:event_tblDatoReparacionMouseClicked

    private void txb_dimensionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txb_dimensionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txb_dimensionesActionPerformed

    private void txb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txb_tipoActionPerformed

    }//GEN-LAST:event_txb_tipoActionPerformed

    private void txb_tipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txb_tipoFocusGained

    }//GEN-LAST:event_txb_tipoFocusGained

    private void tblDatoHornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatoHornoMouseClicked
  
        int filaSeleccionada = tblDatoHorno.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tblDatoHorno.getModel();
        Object idObjeto = modelo.getValueAt(filaSeleccionada, 0);
        txtIDMantenimiento.setText(String.valueOf(idObjeto));
        
    }//GEN-LAST:event_tblDatoHornoMouseClicked

    private void btn_IngresarHornosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarHornosActionPerformed
        try{
            ClaseConsulta INH = new ClaseConsulta();
            horno h= new horno(
                Integer.parseInt(txb_reflectores.getText()),
                txb_tipo.getText(),
                txb_materiales.getText(),
                (String)cb_estadohorno.getSelectedItem(),
                new SimpleDateFormat("yyyy-MM-dd").format(Jd_fecha1.getDate()),
                Double.parseDouble(txb_dimensiones.getText())

            );
            INH.registrarHorno(h);
            tblDatoReparacion.setModel(INH.MostrarHornos());

        }catch(HeadlessException e) {
            JOptionPane.showMessageDialog(this, "error: " + e);
        }
    }//GEN-LAST:event_btn_IngresarHornosActionPerformed

    private void lblMantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimientoMouseClicked
 jPanelHornosSolares.setVisible(false );
    jPanelMantenimiento.setVisible(true);
    jPanelFuncionamiento.setVisible(false);
    jPanelAmbiente.setVisible(false);
    jPanelAutosustentable.setVisible(false); 

    }//GEN-LAST:event_lblMantenimientoMouseClicked

    private void lblHornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHornoMouseClicked
 jPanelHornosSolares.setVisible(true );
    jPanelMantenimiento.setVisible(false);
    jPanelFuncionamiento.setVisible(false);
    jPanelAmbiente.setVisible(false);
    jPanelAutosustentable.setVisible(false); 
    
    }//GEN-LAST:event_lblHornoMouseClicked

    private void lblFuncionamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncionamientoMouseClicked
 jPanelHornosSolares.setVisible(false );
    jPanelMantenimiento.setVisible(false);
    jPanelFuncionamiento.setVisible(true);
    jPanelAmbiente.setVisible(false);
    jPanelAutosustentable.setVisible(false); 
    }//GEN-LAST:event_lblFuncionamientoMouseClicked

    private void lblAmbienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAmbienteMouseClicked
 jPanelHornosSolares.setVisible(false );
    jPanelMantenimiento.setVisible(false);
    jPanelFuncionamiento.setVisible(false);
    jPanelAmbiente.setVisible(true);
    jPanelAutosustentable.setVisible(false); 
    }//GEN-LAST:event_lblAmbienteMouseClicked

    private void lblAutosustentableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAutosustentableMouseClicked
 jPanelHornosSolares.setVisible(false );
    jPanelMantenimiento.setVisible(false);
    jPanelFuncionamiento.setVisible(false);
    jPanelAmbiente.setVisible(false);
    jPanelAutosustentable.setVisible(true); 
    }//GEN-LAST:event_lblAutosustentableMouseClicked

    private void tblDatoMantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatoMantenimientoMouseClicked
int filaSeleccionada = tblDatoMantenimiento.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tblDatoMantenimiento.getModel();
        Object idObjeto = modelo.getValueAt(filaSeleccionada, 0);
        txtIDMantenimiento.setText(String.valueOf(idObjeto)); 

    }//GEN-LAST:event_tblDatoMantenimientoMouseClicked

    private void tblDatoAutosustentableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatoAutosustentableMouseClicked
 int filaSeleccionada = tblDatoAutosustentable.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tblDatoAutosustentable.getModel();
        Object idObjeto = modelo.getValueAt(filaSeleccionada, 0);
        txtIDAutosustentable.setText(String.valueOf(idObjeto));

    }//GEN-LAST:event_tblDatoAutosustentableMouseClicked

    private void btn_IngresarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarMantenimientoActionPerformed
   try{
            ClaseConsulta INGM = new ClaseConsulta();

            mantenimiento m = new mantenimiento(
                Integer.parseInt(txtIDMantenimiento.getText()),
                txb_detallesr.getText(),
                txb_materialesr.getText(),
                new SimpleDateFormat("yyyy-MM-dd").format(Jd_fecha.getDate())
            );
            INGM.InsertarMante(m);
        }catch(HeadlessException e) {
            JOptionPane.showMessageDialog(this, "error: " + e);

        }
    }//GEN-LAST:event_btn_IngresarMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pruebita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pruebita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pruebita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pruebita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pruebita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Jd_fecha;
    private com.toedter.calendar.JDateChooser Jd_fecha1;
    private com.toedter.calendar.JDateChooser Jd_fecha4;
    private com.toedter.calendar.JDateChooser Jd_fecha6;
    private javax.swing.JButton btn_IngresarAmbiente;
    private javax.swing.JButton btn_IngresarAutosustentable;
    private javax.swing.JButton btn_IngresarFuncionamiento;
    private javax.swing.JButton btn_IngresarHornos;
    private javax.swing.JButton btn_IngresarMantenimiento;
    private javax.swing.JComboBox<String> cb_eficienciaenergetica;
    private javax.swing.JComboBox<String> cb_estadohorno;
    private javax.swing.JComboBox<String> cb_estadohorno1;
    private javax.swing.JComboBox<String> cb_tipodealimento;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAmbiente;
    private javax.swing.JPanel jPanelAutosustentable;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelFuncionamiento;
    private javax.swing.JPanel jPanelHornosSolares;
    private javax.swing.JPanel jPanelMantenimiento;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private com.toedter.calendar.JDateChooser jb_fechaoperacion;
    private com.toedter.calendar.JSpinnerDateEditor js_Hora;
    private javax.swing.JSpinner js_energiarecibida;
    private javax.swing.JSpinner js_temperaturai;
    private javax.swing.JLabel lblAmbiente;
    private javax.swing.JLabel lblAutosustentable;
    private javax.swing.JLabel lblFuncionamiento;
    private javax.swing.JLabel lblHorno;
    private javax.swing.JLabel lblMantenimiento;
    private javax.swing.JRadioButton rbAutomatico;
    private javax.swing.JRadioButton rbManual;
    private javax.swing.JTable tblDatoAmbiente;
    private javax.swing.JTable tblDatoAutosustentable;
    private javax.swing.JTable tblDatoFuncionamiento;
    private javax.swing.JTable tblDatoHorno;
    private javax.swing.JTable tblDatoMantenimiento;
    private javax.swing.JTable tblDatoReparacion;
    private javax.swing.JSpinner txb_angulo;
    private javax.swing.JTextField txb_consumoe;
    private javax.swing.JTextArea txb_detallesr;
    private javax.swing.JTextField txb_dimensiones;
    private javax.swing.JComboBox<String> txb_direccion;
    private javax.swing.JTextField txb_energiaalmacenada;
    private javax.swing.JComboBox<String> txb_intensidadsolar;
    private javax.swing.JTextArea txb_materiales;
    private javax.swing.JTextArea txb_materialesr;
    private javax.swing.JTextField txb_reflectores;
    private javax.swing.JSpinner txb_temperatura;
    private com.toedter.calendar.JSpinnerDateEditor txb_tiempoc;
    private javax.swing.JTextField txb_tipo;
    private javax.swing.JTextField txtIDAmbiente;
    private javax.swing.JTextField txtIDAutosustentable;
    private javax.swing.JTextField txtIDFuncionamiento;
    private javax.swing.JTextField txtIDMantenimiento;
    // End of variables declaration//GEN-END:variables
}
